const express = require("express");
const path = require("path");

const complements = [
  "You like nice today",
  "That dress looks nice on you",
  "Have you been working out?",
  "You can do hard things",
  "You've gotten far in this course. You're really smart",
  "You're programming! How cool is that?",
  "I'm really proud of you",
  "You made this",
  "You've learned a lot of things, and that's pretty hard to do"
];

let randomIndex = 0;

function getRandomComplement() {
  randomIndex = Math.floor(Math.random() * complements.length);
  return complements[randomIndex];
}

function getRandomInsult() {
    let rand1 = Math.floor(Math.random() * insult.length);
    let rand2 = Math.floor(Math.random() * insult.length);
    // return console.log(`You are a ${insult[rand1]} ${insult[rand2]}`);
    return insult[rand2];
}

const app = express();

app.get("/", function(req, res) {
  res.sendFile(path.join(__dirname, "index.html"));
});

app.get("/style.css", function(req, res) {
    res.sendFile(path.join(__dirname, "style.css"));
  });

app.get("/complement", function(req, res) {
  res
    .json({
      complement: getRandomComplement()
    })
    .end();
});

app.get("/insult", function(req, res) {
    res
      .json({
        insult: getRandomInsult()
      })
      .end();
  });

app.use("/public", express.static("./public"));

const port = process.env.PORT || 3000;
app.listen(port);
console.log(`listening on http://localhost:${port}`);


const insult = ['You are a aberrant mouth breather', 'You are a amateur cockweasel', 'You are a animal low-life', 'You are a anorak ratfucker', 'You are a ape blubber gut', 'You are a ape covered in human flesh assmunch', 'You are a apefucker cougar', "You are a arfarfan'arf blaggard", 
'You are a arse cuntshit', 'You are a arsebreath cocksucker', 'You are a arsecunt dickhead', 'You are a arseface clown', 'You are a arsehole dickfucker', 'You are a arse-licker numskull', 'You are a ass amateur cockweasel', 'You are a assaholic bimbo', 'You are a assbutt dogfucker', 'You are a ass clown ninnyhammer', 'You are a asscunt klutz', 
'You are a assface birdbrain', 'You are a assfag lamebrain', 'You are a assfaggot cuckold', 'You are a assfucker bum-fucker', 'You are a asshat Cad', 'You are a asshole dogbolt', 'You are a ass-kisser burden', 'You are a ass-licker lunatic', 'You are a assmonkey dirtbag', 
'You are a assmouth liar', 'You are a assmunch cockholster', 'You are a ass-nugget jamoke', 'You are a ass sucker louse', 'You are a asstard daughterfucker', 'You are a asswagon assfucker bum-fucker', 'You are a assweed nonce', 'You are a asswipe ignoramus', 'You are a aunt fucker fuckhead', 'You are a baby fucktoy', 
'You are a backwoodsman cockhead', 'You are a badass boob', 'You are a badgerfucker fishwife', 'You are a bag of dicks badass boob', 'You are a Bag whore bootlicker', 'You are a ballkicker Mr. Struggle', 'You are a ballsack duckfucker', 'You are a bandit buffoon', 'You are a bangsat fool', 'You are a barbarian dunce', 
'You are a Barbie-fucker fag', 'You are a bastard megadouche', 'You are a Bawtboy ratfink', 'You are a bean head ass-kisser burden', 'You are a beast arsebreath cocksucker', 'You are a beetlehead cum-licker', 'You are a beginner nitwit', 'You are a beldame cuntbiscuit', 'You are a bell-end dickface', 'You are a berk faggot', 
'You are a bespawler querulant', 'You are a Beta cuck hog', 'You are a bimbo fucklord', 'You are a birdbrain cuntbitch', 'You are a birdfucker asstard daughterfucker', 'You are a bitch bumbo', 'You are a bitchass bum chum', 'You are a bitch ass motherfucker dumbass', 'You are a bitch boy bimbo fucklord', 'You are a bitchcunt dickhead', 
'You are a bitchdicksucker arseface clown', 'You are a bitchface biznatch', 'You are a bitchfucker dummy', 'You are a bitchtits idiotist', 'You are a bitchwad dickfucker', 'You are a bitchwhore nonce', 'You are a bitchzilla ass sucker louse', 'You are a biznatch cuntfucker', 'You are a blackguard cougar', 'You are a blaggard incel', 'You are a blockhead greeniac', 
'You are a blubber gut queer', 'You are a bluntie country bumpkin', 'You are a bogeyman nephew fucker', 'You are a bonehead dummy', 'You are a boob ruffian', 'You are a booby bugfucker', 'You are a boomer dimmadumbass', 'You are a bootlicker bum chum', 'You are a boozer scumface', 'You are a boyfucker hoe', 'You are a bozo bitchfucker dummy', 'You are a brainlet pube flosser', 
'You are a brickfucker beginner nitwit', 'You are a brickhead craphole', 'You are a brotherfucker cockmaster', 'You are a buffoon hooplehead', 'You are a bugfucker dumbass', 'You are a bugger con merchant', 'You are a bullfuck cockwaddle', 'You are a bum buffoon hooplehead', 'You are a bumbo monster', 'You are a bum chum rat', 'You are a bum-fucker cuntzilla', 
'You are a burden libtard', 'You are a buttass gaywad', 'You are a buttbreath birdfucker asstard daughterfucker', 'You are a buttfucker porno freak', 'You are a butthead bitchass bum chum', 'You are a butthole fatty', 'You are a buttkisser beetlehead cum-licker', 'You are a buttlicker landwhale', 'You are a buttmunch douche', 'You are a butt sniffer arsebreath cocksucker', 
'You are a Cad gawk', 'You are a camelfucker cum-licker', 'You are a catfucker grouch', 'You are a caveman jagweed', 'You are a chauvinist buttkisser beetlehead cum-licker', 'You are a chav mutant', 'You are a cheater douchefag', 'You are a chicken earthworm', 'You are a chickenfucker jamoke', 'You are a childfucker potato', 'You are a chode cumbucket', 'You are a chump goof', 
'You are a churl monkeyface', 'You are a clitbag queer bait', 'You are a clithead cockmaster', 'You are a Clod imbecile', 'You are a clown dumb fucker', 'You are a cock noodle', 'You are a cockalorum intercourser', 'You are a cockboy corpsefucker', 'You are a cockburger dick', 'You are a cockfucker fucktoy', 'You are a cockhead kidfucker', 'You are a cockholster buttkisser beetlehead cum-licker', 
'You are a cockmaster ratcatcher', 'You are a cockroach gorilla', 'You are a cocksucker fuckstain', 'You are a cocktease douchewad', 'You are a cockwaddle fuckass', 'You are a cockweasel nitwit', 'You are a cockwomble jackass', 'You are a coffee slurper bitchtits idiotist', 'You are a con man muppet', 'You are a con merchant grumpy', 'You are a coomer fugly', 'You are a corpsefucker assfag lamebrain',
 'You are a cougar bimbo fucklord', 'You are a country bumpkin reject', 'You are a cousinfucker failed abortion', 'You are a cow motherfucker', 'You are a coward imbecile', 'You are a cowfucker kidfucker', 'You are a crackhead fatass', 'You are a crack whore bitchtits idiotist', 'You are a craphole rat', 'You are a creep fucknose', 'You are a cretin donkey', 'You are a cro magnon non', 
 'You are a crook earthworm', 'You are a cuckold fag', 'You are a cumbucket pukeball', 'You are a cum dumpster cum-licker', 'You are a cum guzzler assmouth liar', 'You are a cum-licker animal low-life', 'You are a cumslut bitchzilla ass sucker louse', 'You are a cumstain nincompoop', 'You are a cunt butthead bitchass bum chum', 'You are a cuntass goon', 
 'You are a cuntbiscuit mamzer', 'You are a cuntbitch Bag whore bootlicker', 'You are a cuntbreath dogbolt', 'You are a cuntface ding-head', 'You are a cunt fart cuntfucker', 'You are a cuntfucker lickspittle', 'You are a cuntlicker lard face', 'You are a cunt muncher edgelord', 'You are a cunt rag missing link', 'You are a cuntshit dimmadumbass', 'You are a cuntsucker dweebling', 
 'You are a cuntzilla churl monkeyface', 'You are a dandiprat chump goof', 'You are a daughterfucker intercourser', 'You are a deadhead missing link', 'You are a degenerate retard', 'You are a der-brain bitchwad dickfucker', 'You are a desperado dirtbag', 'You are a devil caveman jagweed', 'You are a dick fucklord', 'You are a dickass helldog', 'You are a dickbag farmer', 'You are a dickbreath ratfink', 
 'You are a dickcheese jagweed', 'You are a dickface mung', 'You are a dickfucker fish', 'You are a dickhead ballsack duckfucker', 'You are a dickhole dickfucker fish', 'You are a dickless nincompoop', 'You are a dicklicker dope', 'You are a dick man dirthead', 'You are a dick mouth megabitch', 'You are a dick sniffer egghead', 'You are a dicksplash birdbrain cuntbitch', 'You are a dick-sucker riff-raff',
  'You are a dicktard dick fucklord', 'You are a dickwad grumpy', 'You are a dickweasel con merchant grumpy', 'You are a dick weed cuntsucker dweebling', 'You are a dildo numpty', 'You are a dillhole bangsat fool', 'You are a dimmadumbass butthead bitchass bum chum', 'You are a dimwit farmer', 'You are a ding-head mutant', 'You are a dingleberry Bawtboy ratfink', 'You are a dinosaur ratcatcher', 'You are a dipfuck assfucker bum-fucker', 
  'You are a dipshit hooplehead', 'You are a dirtbag dogfucker', 'You are a dirthead assfucker bum-fucker', 'You are a dirtwad megadouche', 'You are a dodo dickhole dickfucker fish', 'You are a dog con man muppet', 'You are a dogbolt roaster', 'You are a dogbreath gimp', 'You are a dogfucker duckfucker', 'You are a dolt cockweasel nitwit', 'You are a donkey bitchtits idiotist', 'You are a donkey dick Bag whore bootlicker', 'You are a donkeyfucker fuckbucket', 
  'You are a doofus keyboard warrior', 'You are a dope desperado dirtbag', 'You are a dotterel dirtbag dogfucker', 'You are a douche dolt cockweasel nitwit', 'You are a douche bag dummy', 'You are a doucheburger cockweasel nitwit', 'You are a douche canoe milksop', 'You are a douchefag cougar bimbo fucklord', 'You are a douchelord Ryan-cheetoh-head', 'You are a douche nozzle duckfucker', 'You are a douchewad bastard megadouche', 'You are a douchewagon monkey', 
  'You are a dracula hog', 'You are a dreamer dope desperado dirtbag', 'You are a drunkard missing link', 'You are a duckfucker mouth breather', 'You are a dumbarse dolt cockweasel nitwit',
  'You are a dumbass monkey', 'You are a dumbbell fanny', 'You are a dumb fucker rowdy', 'You are a dumbo hussy', 'You are a dummy chump goof', 'You are a dunce dicktard dick fucklord', 'You are a duncebucket dreamer dope desperado dirtbag', 'You are a dweebling cocksucker fuckstain', 'You are a earthworm numskull', 'You are a edgelord blackguard cougar', 'You are a egghead aunt fucker fuckhead', 'You are a egotist burden libtard', 'You are a envirotard fanny',
   'You are a eunuch jerk', 'You are a fag dumbbell fanny', 'You are a faggot raasclaat', 'You are a faggotface gawk', 'You are a fagtard clown dumb fucker', 'You are a fagtits mental midget', 'You are a failed abortion ass-kisser burden', 'You are a fanny duckfucker mouth breather', 'You are a farmer cum-licker animal low-life', 'You are a fart cunt butthead bitchass bum chum', 'You are a fartface Clod imbecile', 'You are a fatass ho', 'You are a fatfuck scoundrel', 
   'You are a fat geezer assfucker bum-fucker', 'You are a fatherfucker mouth breather', 'You are a fatso assfag lamebrain', 'You are a fat-tard keyboard warrior', 'You are a fatty cockhead kidfucker', 'You are a fellow cuntbitch Bag whore bootlicker', 'You are a fetus cowfucker kidfucker', 'You are a fibber dolt cockweasel nitwit', 'You are a fink cockfucker fucktoy', 'You are a fish cuntzilla churl monkeyface', 'You are a fish fucker redditor', 'You are a fishwife cunt rag missing link', 
   'You are a fixer mackerel', 'You are a flake lunatic', 'You are a fool cocktease douchewad', 'You are a freak grouch', 'You are a fruitcake coomer fugly', 'You are a fuck mutt', 'You are a fuckass Nebbish', 'You are a fuckbait numbnuts', 'You are a fuckbucket dweebling cocksucker fuckstain', 'You are a fucker buttlicker landwhale', 'You are a fuckface joker', 'You are a fuckhead Mingie', 'You are a fucking bitch dracula hog', 'You are a fucklord nobody', 'You are a fuck noggin nobody', 
   'You are a fucknose douchelord Ryan-cheetoh-head', 'You are a fuck nugget scumlord', 'You are a fuckrod landwhale', 'You are a fuckshit bitchzilla ass sucker louse', 'You are a fuckskull clithead cockmaster', 'You are a fuckstain fucker buttlicker landwhale', 'You are a fuckster poohead', 'You are a fucktard karen', 'You are a fucktoy moron', 'You are a fuckweasel beginner nitwit', 'You are a fuckwhistle dickwad grumpy', 'You are a fuckwit dodo dickhole dickfucker fish', 
   'You are a fugly dimmadumbass butthead bitchass bum chum', 'You are a gawk intercourser', 'You are a gaytard con merchant grumpy', 'You are a gaywad arsebreath cocksucker', 'You are a geebag ding-head mutant', 'You are a gimp cheater douchefag', 'You are a git missing link', 'You are a gobshite fatass ho', 'You are a gold digger nerf herder', 'You are a goof hog', 'You are a goon jerkoff', 'You are a goose gorilla', 'You are a gorilla ass-licker lunatic', 
   'You are a grandmotherfucker moron', 'You are a greeniac git missing link', 'You are a grouch clitbag queer bait', 'You are a grumpy fibber dolt cockweasel nitwit', 'You are a handfucker envirotard fanny', 'You are a headass dandiprat chump goof', 'You are a helldog hog', 'You are a hikikomori assfag lamebrain', 'You are a hilding berk faggot', 'You are a hillbilly chauvinist buttkisser beetlehead cum-licker', 'You are a hippie cumbucket pukeball',
    'You are a ho dodo dickhole dickfucker fish', 'You are a hobbledehoy buttlicker landwhale', 'You are a hoe fag dumbbell fanny', 'You are a hog Mr. Anger', 'You are a homo hippie cumbucket pukeball', 'You are a hooligan arse cuntshit', 'You are a hooplehead asstard daughterfucker', 'You are a horsefucker nitwit', "You are a horse's ass buttbreath birdfucker asstard daughterfucker", "You are a horse's necktie beginner nitwit", 
    'You are a hosebag lickspittle', 'You are a hussy anorak ratfucker', 'You are a hypocrite donkey dick Bag whore bootlicker', 'You are a idiot geebag ding-head mutant', 'You are a idiotist der-brain bitchwad dickfucker', 'You are a idiot sandwich fucktard karen', 'You are a ignoramus fagtard clown dumb fucker', 'You are a imbecile scumface', 'You are a inbred idiot sandwich fucktard karen', 'You are a incel fuckwhistle dickwad grumpy', 
    'You are a intercourser fuckskull clithead cockmaster', 'You are a jabroni cum dumpster cum-licker', 'You are a jackass blackguard cougar', 'You are a jackhole mackerel', 'You are a jackwagon degenerate retard', 'You are a jagweed mongoose', 'You are a jamoke fatherfucker mouth breather', 'You are a jelly cheater douchefag', 'You are a jerk dick fucklord', 'You are a jerkoff ratfucker', 'You are a jerkwad aberrant mouth breather', 
    'You are a jit stain numbskull', 'You are a jizz guzzler cockweasel nitwit', 'You are a joker bogeyman nephew fucker', 'You are a junkie loser', 'You are a karen ballsack duckfucker', 'You are a kevun nerd', 'You are a keyboard warrior craphole rat', 'You are a kidfucker idiot geebag ding-head mutant', 'You are a klutz beldame cuntbiscuit', 'You are a lady of the evening faggotface gawk', 'You are a lamebrain asshat Cad',
     'You are a landwhale assfaggot cuckold', 'You are a langer monster', 'You are a lard face nerf herder', 'You are a liar bitchfucker dummy', 'You are a libtard grandmotherfucker moron', 'You are a lickspittle fucker buttlicker landwhale', 'You are a lobotomite birdfucker asstard daughterfucker', 'You are a loser robot', 'You are a louse clitbag queer bait', 'You are a low-life faggotface gawk', 'You are a lunatic pussyfucker', 
     'You are a lunkhead pussy pisser', 'You are a lurdane fibber dolt cockweasel nitwit', 'You are a lush loser robot', 'You are a mackerel milksop', 'You are a madman imbecile scumface', 'You are a maggot poohead', 'You are a mamzer buttkisser beetlehead cum-licker', 'You are a meanie potato', 'You are a megabitch mutant', 'You are a megadouche daughterfucker intercourser', 'You are a mental midget rowdy', 'You are a milksop fish fucker redditor', 
     'You are a Mingie cockmaster ratcatcher', 'You are a minx bogeyman nephew fucker', 'You are a missing link buffoon hooplehead', 'You are a mongoose intercourser fuckskull clithead cockmaster', 'You are a monkey buttbreath birdfucker asstard daughterfucker', 'You are a monkeyface cocktease douchewad', 'You are a monster jelly cheater douchefag', 'You are a mooncalf fuckstain fucker buttlicker landwhale', 'You are a moron dummy chump goof', 
     'You are a motherfucker scumlord', 'You are a mousefucker dipfuck assfucker bum-fucker', 'You are a mouth breather bitchtits idiotist', 'You are a Mr. Anger chump goof', 'You are a Mr. Obsessed monkeyface cocktease douchewad', 'You are a Mr. Struggle jackwagon degenerate retard', 'You are a Mr. Talk dumbass monkey', 'You are a mucky pup birdbrain cuntbitch', 'You are a mumpsimus runt', 'You are a mung loser robot', 'You are a muppet low-life faggotface gawk', 
     'You are a mutant cuntsucker dweebling', 'You are a mutt devil caveman jagweed', 'You are a neanderthal pseudo-intellectual', 'You are a Nebbish dumbo hussy', 'You are a neckbeard fool cocktease douchewad', 'You are a necrophiliac quat', "You are a ne'er-do-well dog con man muppet", 'You are a nephew fucker donkeyfucker fuckbucket', 'You are a nerd chauvinist buttkisser beetlehead cum-licker', 'You are a nerf herder dickfucker fish', 'You are a niece fucker klutz beldame cuntbiscuit',
      'You are a nigger gaytard con merchant grumpy', 'You are a nimrod fat geezer assfucker bum-fucker', 'You are a nincompoop cockholster buttkisser beetlehead cum-licker', 'You are a ninny fugly dimmadumbass butthead bitchass bum chum', 'You are a ninnyhammer fuckhead Mingie', 'You are a nitwit beginner nitwit', 'You are a nobody Mr. Talk dumbass monkey', 'You are a non fatty cockhead kidfucker', 'You are a nonce coomer fugly', 
      'You are a noob arsehole dickfucker', 'You are a noodle cum guzzler assmouth liar', 'You are a numbnuts assfucker bum-fucker', 'You are a numbskull egotist burden libtard', 'You are a numpty porno freak', 'You are a numskull madman imbecile scumface', 'You are a poohead chauvinist buttkisser beetlehead cum-licker', 'You are a poop hole ass-kisser burden', 'You are a porno freak inbred idiot sandwich fucktard karen', 'You are a potato dweebling cocksucker fuckstain',
       'You are a prick douche nozzle duckfucker', 'You are a prickface cock noodle', 'You are a pseudo-intellectual Mr. Talk dumbass monkey', 'You are a pube flosser nitwit beginner nitwit', 'You are a pudwhacker dicktard dick fucklord', 'You are a puke bag fucknose douchelord Ryan-cheetoh-head', 'You are a pukeball cousinfucker failed abortion', 'You are a puppet rabbitfucker', 'You are a pussy brickhead craphole', 'You are a pussyboy scumlord', 'You are a pussyfucker Mingie cockmaster ratcatcher', 
       'You are a pussy pisser hog Mr. Anger', 'You are a quack dimwit farmer', 'You are a quat sadist', 'You are a queer bean head ass-kisser burden', 'You are a queer bait brickhead craphole', 'You are a querulant Mr. Struggle jackwagon degenerate retard', 'You are a raasclaat beldame cuntbiscuit', 'You are a rabbitfucker cuntzilla churl monkeyface', 'You are a rat assbutt dogfucker', 'You are a ratcatcher fuckwhistle dickwad grumpy', 'You are a ratfink dog con man muppet', 'You are a ratfucker blockhead greeniac', 
       'You are a redditor dickhead ballsack duckfucker', 'You are a redneck cunt rag missing link', 'You are a reject cuntfucker lickspittle', 'You are a retard cuntass goon', 'You are a riff-raff mongoose intercourser fuckskull clithead cockmaster', 'You are a roaster dickface mung', 'You are a robot Mingie cockmaster ratcatcher', 'You are a rowdy necrophiliac quat', 'You are a rudesby Sam Rea', 'You are a ruffian arsecunt dickhead', 'You are a runt Bag whore bootlicker', 'You are a Ryan-cheetoh-head cockfucker fucktoy',
        'You are a sadist cockboy corpsefucker', 'You are a Sam Rea fixer mackerel', 'You are a saprophyte dinosaur ratcatcher', 'You are a sausage-masseuse necrophiliac quat', 'You are a scobberlotcher ratcatcher fuckwhistle dickwad grumpy', 'You are a scoozie buttmunch douche', 'You are a scoundrel idiotist der-brain bitchwad dickfucker', 'You are a scumbag saprophyte dinosaur ratcatcher', 'You are a scumbreath dipfuck assfucker bum-fucker', 'You are a scumbutt arsebreath cocksucker', 'You are a scumface cuntbitch Bag whore bootlicker', 
        'You are a scumfuck fucknose douchelord Ryan-cheetoh-head', 'You are a scumhead eunuch jerk', 'You are a scumlord scumface cuntbitch Bag whore bootlicker', 'You are a scumwad ratfink dog con man muppet', 'You are a scuzzbag fuckhead Mingie', 'You are a serf fucktard karen', 'You are a sewer rat dirtbag dogfucker', 'You are a shark scobberlotcher ratcatcher fuckwhistle dickwad grumpy', 'You are a sheepfucker dicksplash birdbrain cuntbitch', 'You are a sheepshagger numskull madman imbecile scumface', 'You are a shill dumbarse dolt cockweasel nitwit', 
        'You are a shitass chickenfucker jamoke', 'You are a shitbag dumbass monkey', 'You are a shitball fuckskull clithead cockmaster', 'You are a shitbird cuntfucker lickspittle', 'You are a shitbrain biznatch cuntfucker', 'You are a shitbreath horsefucker nitwit', 'You are a shitbucket ape blubber gut', 'You are a shitbum dumbo hussy', 'You are a shitcunt apefucker cougar', 'You are a shitdick animal low-life', 'You are a shit-eater intercourser fuckskull clithead cockmaster', 'You are a shitehawk fugly dimmadumbass butthead bitchass bum chum', 'You are a shitface cuntshit dimmadumbass', 
        'You are a shit-for-brains fatherfucker mouth breather', 'You are a shitfuck dandiprat chump goof', 'You are a shitfucker puppet rabbitfucker', 'You are a shitgoblin arse-licker numskull', 'You are a shithead bean head ass-kisser burden', 'You are a shitizen ballkicker Mr. Struggle', 'You are a shitlord bastard megadouche', 'You are a shitneck fucktard karen', 'You are a shitnugget brotherfucker cockmaster', 'You are a shitpicker cocksucker fuckstain', 'You are a shitpiss fuck noggin nobody', 'You are a shitpot asswagon assfucker bum-fucker', 
        'You are a shitpuddle dirthead assfucker bum-fucker', 'You are a shitsack landwhale assfaggot cuckold', 'You are a shit stain git missing link', 'You are a shitter inbred idiot sandwich fucktard karen', 'You are a shitweasel chicken earthworm', 'You are a shmekl lush loser robot', 'You are a shrew fucking bitch dracula hog', 'You are a shyster arse-licker numskull', 'You are a sibling fucker hog Mr. Anger', 'You are a simp lurdane fibber dolt cockweasel nitwit', 'You are a simpleton cuntass goon', 'You are a sisterfucker bitchdicksucker arseface clown', 
        'You are a sister humper dirthead assfucker bum-fucker', 'You are a skank fuckwhistle dickwad grumpy', 'You are a sket asswipe ignoramus', 'You are a skite baby fucktoy', 'You are a skullfucker dumbass monkey', 'You are a skunk hog Mr. Anger', 'You are a skunkfucker homo hippie cumbucket pukeball', 'You are a slag karen ballsack duckfucker', 'You are a slave riff-raff mongoose intercourser fuckskull clithead cockmaster', 'You are a sleazewad hooplehead asstard daughterfucker', 'You are a sleeze chode cumbucket', 'You are a sleeze bag dimmadumbass butthead bitchass bum chum',
         'You are a slimeface ape covered in human flesh assmunch', 'You are a slob dreamer dope desperado dirtbag', 'You are a slut douche nozzle duckfucker', 'You are a slutfucker gaytard con merchant grumpy', 'You are a sluthead dandiprat chump goof', 'You are a smell-feast dope desperado dirtbag', 'You are a smellfungus dirthead assfucker bum-fucker', 'You are a snail libtard grandmotherfucker moron', 'You are a snake cum-licker animal low-life', 'You are a snob bum chum rat', 'You are a snollygoster pube flosser nitwit beginner nitwit', 'You are a snot gimp cheater douchefag',
          'You are a snotball douche nozzle duckfucker', 'You are a snotface dickbreath ratfink', 'You are a snothead cheater douchefag', 'You are a snotwad egotist burden libtard', 'You are a snowflake country bumpkin reject', 'You are a son of a bitch dope desperado dirtbag', 'You are a son of a motherless goat booby bugfucker', 'You are a son of a whore cuntass goon', 'You are a sow blaggard incel', 'You are a soy boy fatass ho', 'You are a spack dipshit hooplehead', 'You are a sped brotherfucker cockmaster', 'You are a sphincter nerd chauvinist buttkisser beetlehead cum-licker', 
          'You are a splenetic louse clitbag queer bait', "You are a square horse's ass buttbreath birdfucker asstard daughterfucker", 'You are a stink cunt motherfucker scumlord', 'You are a stinker megabitch mutant', 'You are a stinkhole faggotface gawk', 'You are a straggot farmer cum-licker animal low-life', 'You are a stupid scoundrel idiotist der-brain bitchwad dickfucker', 'You are a swindler bitch ass motherfucker dumbass', 'You are a swine fatfuck scoundrel', 'You are a sycophant niece fucker klutz beldame cuntbiscuit', 'You are a thief kidfucker idiot geebag ding-head mutant', 
          'You are a thotpocket chauvinist buttkisser beetlehead cum-licker', 'You are a thundercunt dick weed cuntsucker dweebling', 'You are a Tit gawk intercourser', 'You are a titbag cunt rag missing link', 'You are a toad scobberlotcher ratcatcher fuckwhistle dickwad grumpy', 'You are a Toe Eyed Cabbage lunkhead pussy pisser', 'You are a tomato fuckhead Mingie', 'You are a tool scumlord scumface cuntbitch Bag whore bootlicker', 'You are a tree hugger dirtbag dogfucker', 'You are a troglodyte intercourser fuckskull clithead cockmaster', 'You are a troll lickspittle fucker buttlicker landwhale', 
          'You are a trollface jagweed mongoose', 'You are a trolltard coomer fugly', 'You are a turd ballsack duckfucker', 'You are a turdball backwoodsman cockhead', 'You are a turdbucket catfucker grouch', 'You are a turdpile asscunt klutz', 'You are a twat fuck noggin nobody', 'You are a twattock scumlord scumface cuntbitch Bag whore bootlicker', 'You are a twatwaffle ass amateur cockweasel', 'You are a twerp klutz beldame cuntbiscuit', 'You are a twit goon jerkoff', 'You are a twunt hog Mr. Anger', 'You are a unclefucker noodle cum guzzler assmouth liar', 'You are a vagina cleaner creep fucknose',
           'You are a vampire bum-fucker cuntzilla', 'You are a vandal cock noodle', 'You are a vantz arsebreath cocksucker', 'You are a varmint dimmadumbass butthead bitchass bum chum', 'You are a vermin bitchfucker dummy', 'You are a vonce ratfink dog con man muppet', 'You are a wacko nitwit beginner nitwit', 'You are a wallflower noob arsehole dickfucker', 'You are a wally prick douche nozzle duckfucker', 'You are a wanker nitwit beginner nitwit', 'You are a wank stain mutt devil caveman jagweed', 'You are a Wazzock fishwife cunt rag missing link', 
           'You are a weeze bag hilding berk faggot', 'You are a weirdo dolt cockweasel nitwit', 'You are a whore neckbeard fool cocktease douchewad', 'You are a whorefucker ballkicker Mr. Struggle', 'You are a whoreson douche nozzle duckfucker', 'You are a windfucker fixer mackerel', 'You are a windsucker buttlicker landwhale', 'You are a wino cowfucker kidfucker', 'You are a witch envirotard fanny', 'You are a womanizer chauvinist buttkisser beetlehead cum-licker', 'You are a wommy dogbolt roaster', 'You are a worm noob arsehole dickfucker', 
           'You are a wretch aberrant mouth breather', 'You are a xenophobe asswagon assfucker bum-fucker', 'You are a yahoo fart cunt butthead bitchass bum chum', 'You are a yes-man beldame cuntbiscuit', 'You are a yiffer cockweasel nitwit', 'You are a yonker arsebreath cocksucker', 'You are a yutz buttkisser beetlehead cum-licker', 'You are a zebrafucker butthole fatty', 'You are a zitface bootlicker bum chum', 'You are a zoophile loser robot', 'You are a zounderkite fartface Clod imbecile'];